# -*- coding: utf-8 -*-
"""pregunta2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b2IAmRzutqTLFMEUnObk95do63TCQwJt

estructura secuenciales
"""

precio = float(input("ingrese el precio del producto:"))
cantidad = int(input("ingrese la cantidad comprada:"))

subtotal = precio * cantidad
igv = subtotal * 0.18
total = subtotal + igv

print("/n--- RESULTADOS ---")
print("subtotal:", subtotal)
print("igv (18%):", igv)
print("total a pagar:", total)