# -*- coding: utf-8 -*-
"""pregunta3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYMvushhsgbqcRxPbxThYTAtqei5j-Mu
"""

while True:
  nombre = input("ingrese el nombre del estudiante (o FIN para salir):")

  if nombre.upper() == "FIN":
    break

  n1 = float(input("ingrese la primera nota:"))
  n2 = float(input("ingrese la segunda nota:"))
  n3 = float(input("ingrese la tercera nota:"))

  promedio = (n1 + n2 + n3) / 3

  if promedio <= 10:
    estado = "desaprobado"
  elif promedio <= 14:
    estado = "recuperacion"
  else:
    estado = "aprobado"
  print(f"hola {nombre}, tu estado es: {estado}/n")